version: '3.7'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "./database:/var/lib/mysql"
    ports:
      - 3306:3306
  db_pma:
    image: phpmyadmin/phpmyadmin:5
    depends_on:
      - db
    ports:
      - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_USER: root
      PMA_PASSWORD: password
  www:
    build:
      context: ./php
      dockerfile: Dockerfile
    links:
      - db
    volumes:
      - "./www:/var/www/html"
    ports:
      - 8080:80
